apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: eda-app
spec:
  selector:
    app: zookeeper # Doit correspondre aux labels du Pod Zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP 