apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: eda-app
data:
  # URL de connexion JDBC pour PostgreSQL
  # Utilise le nom du service postgres, le port, et le nom de la BDD défini dans le déploiement PG
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service.eda-app.svc.cluster.local:5432/edadb"

  # Adresse du broker Kafka
  # Utilise le nom du service kafka et son port
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service.eda-app.svc.cluster.local:9092"

  # Vous pouvez ajouter d'autres configurations ici si nécessaire
  # Exemple: Noms des topics Kafka
  # KAFKA_TOPIC_ORDERS: "orders-topic"
  # KAFKA_TOPIC_NOTIFICATIONS: "notifications-topic" 